source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

# def toolkit_name
#   'JWTDesktopSwiftToolkit'
# end

def target_name
  'JWTSwiftUI'
end

def test_name
  target_name + 'Tests'
end

def handmade
  pod 'JWT', path: '../../'
end

def all
  [target_name]
end

def install_all
  all.each do |t|
    target t do
      use_frameworks!
      handmade
    end
  end
end

install_all
# target test_name do
#   handmade
# end
