source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

def toolkit_name
  'JWTDesktopSwiftToolkit'
end

def target_name
  'JWTDesktopSwift'
end

def test_name
  target_name + 'Tests'
end

def handmade
  pod 'JWT', path: '../../'
  pod 'SnapKit' #, '~> 3.0'
  # pod 'Masonry'
end

def all
  [toolkit_name, target_name]
end

def install_all
  all.each do |t|
    target t do
      use_frameworks!
      handmade
    end
  end
end

install_all
# target test_name do
#   handmade
# end
